"""Render typed PairBlock declarations as deterministic human review pages.

The declaration manifest and lifecycle receipts supply every rendered value.
This module owns presentation only: it replaces two marked Markdown regions
and can reject hand edits inside them. Execution metadata flows from typed
records into Markdown; the controller reads the typed records directly.
"""

from __future__ import annotations

import os
import shlex
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

from .declaration_manifest import GateCommand, PairBlock, ProjectDeclarations
from .profile import ChecklistProfile, PairBlockGateError

CONTRACT_REGION = "manifest-native-contract"
CHECKLIST_REGION = "manifest-native-checklist"


@dataclass(frozen=True, slots=True)
class PairBlockView:
    """Supply receipt-derived state to the Markdown renderer.

    Attributes:
        status: Current project lifecycle label.
        receipt: Repository-relative current receipt path, when one exists.
    """

    status: str
    receipt: str | None = None


@dataclass(frozen=True, slots=True)
class RenderedMarkdown:
    """Contain the complete rendered contract and checklist bytes.

    Attributes:
        contract: Governing contract with its generated region replaced.
        checklist: Execution checklist with its generated region replaced.
    """

    contract: bytes
    checklist: bytes


def render_markdown(
    repository: Path,
    declarations: ProjectDeclarations,
    views: dict[str, PairBlockView],
    profile: ChecklistProfile,
    *,
    check: bool = False,
) -> RenderedMarkdown:
    """Render or verify the contract and checklist regions as one projection.

    ``views`` must contain exactly one receipt-derived state for each declared
    PairBlock. With ``check=True``, the function compares the stored regions
    with the deterministic projection and raises ``PairBlockGateError`` on any
    manual change.
    """

    expected_ids = set(declarations.pair_blocks_by_id)
    if set(views) != expected_ids:
        raise PairBlockGateError(
            "render views must name exactly the manifest-native PairBlocks"
        )
    contract_path = repository / profile.contract_path
    checklist_path = repository / profile.checklist_path
    contract_text = contract_path.read_text(encoding="utf-8")
    checklist_text = checklist_path.read_text(encoding="utf-8")
    contract_region = _render_contract_region(repository, declarations, views, profile)
    checklist_region = _render_checklist_region(
        repository, declarations, views, profile
    )
    contract = _replace_region(
        contract_text, CONTRACT_REGION, contract_region, check=check
    )
    checklist = _replace_region(
        checklist_text, CHECKLIST_REGION, checklist_region, check=check
    )
    return RenderedMarkdown(contract.encode(), checklist.encode())


def _replace_region(text: str, name: str, content: str, *, check: bool) -> str:
    """Replace one unique generated region or reject stale generated bytes."""

    start = f"<!-- generated:{name}:start -->"
    end = f"<!-- generated:{name}:end -->"
    if text.count(start) != 1 or text.count(end) != 1:
        raise PairBlockGateError(f"document needs one {name} generated region")
    before, remainder = text.split(start, 1)
    current, after = remainder.split(end, 1)
    expected = f"\n{content.rstrip()}\n"
    if check and current != expected:
        raise PairBlockGateError(f"{name} generated region differs from declarations")
    return f"{before}{start}{expected}{end}{after}"


def _render_contract_region(
    repository: Path,
    declarations: ProjectDeclarations,
    views: dict[str, PairBlockView],
    profile: ChecklistProfile,
) -> str:
    """Render review details for every manifest-native PairBlock."""

    if not declarations.pair_blocks:
        return "_No manifest-native PairBlocks._"
    requirements = declarations.requirements_by_id
    verifiers = declarations.verifiers_by_id
    blocks: list[str] = []
    for block in sorted(declarations.pair_blocks, key=lambda item: item.id):
        view = views[block.id]
        requirement_lines = [
            f"- `{record.id}`: {record.claim}"
            for record in (requirements[item] for item in block.requirement_ids)
        ]
        verifier_ids = {
            verifier_id
            for requirement_id in block.requirement_ids
            for verifier_id in requirements[requirement_id].verifier_ids
        }
        condition_lines = [
            f"- `{verifier_id}`: {condition}"
            for verifier_id in sorted(verifier_ids)
            for condition in verifiers[verifier_id].conditions
        ]
        source_links = _implementation_links(
            repository,
            repository / profile.contract_path,
            block,
            profile,
        )
        dependencies = ", ".join(f"`{item}`" for item in block.depends_on) or "None"
        receipt = _receipt_link(
            repository, repository / profile.contract_path, view.receipt
        )
        blocks.append(
            "\n".join(
                (
                    f"#### Manifest-native block {block.id}",
                    "",
                    f"**Status:** {view.status}",
                    "",
                    "**Requirements:**",
                    "",
                    *requirement_lines,
                    "",
                    "**Verifier conditions:**",
                    "",
                    *condition_lines,
                    "",
                    f"**Dependencies:** {dependencies}",
                    "",
                    f"**Implementation:** {source_links}",
                    "",
                    f"**Current receipt:** {receipt}",
                    "",
                    "**Gate:**",
                    "",
                    "```bash",
                    _shell_command(
                        repository,
                        block.gate,
                        dict(profile.repository_roots),
                    ),
                    "```",
                    "",
                    "**Next transition:**",
                    "",
                    "```bash",
                    _next_transition(repository, block.id, view.status, profile),
                    "```",
                )
            )
        )
    return "\n\n".join(blocks)


def _render_checklist_region(
    repository: Path,
    declarations: ProjectDeclarations,
    views: dict[str, PairBlockView],
    profile: ChecklistProfile,
) -> str:
    """Render the operator table for manifest-native PairBlocks."""

    if not declarations.pair_blocks:
        return "_No manifest-native PairBlocks._"
    header = (
        "| PairBlock | Status | Depends on | Contract | Source | Tests | Receipt |\n"
        "|---|---|---|---|---|---|---|"
    )
    rows = [header]
    for block in sorted(declarations.pair_blocks, key=lambda item: item.id):
        view = views[block.id]
        dependencies = ", ".join(f"`{item}`" for item in block.depends_on) or "None"
        contract_link = _link(
            repository / profile.checklist_path,
            repository / profile.contract_path,
            block.id,
            f"manifest-native-block-{block.id.lower()}",
        )
        owner = (
            repository / dict(profile.repository_roots)[block.repository]
        ).resolve()
        source = " · ".join(
            _link(repository / profile.checklist_path, owner / item, Path(item).name)
            for item in block.source_paths
        )
        tests = " · ".join(
            _link(repository / profile.checklist_path, owner / item, Path(item).name)
            for item in block.test_paths
        )
        receipt = _receipt_link(
            repository,
            repository / profile.checklist_path,
            view.receipt,
        )
        rows.append(
            f"| `{block.id}` | {view.status} | {dependencies} | {contract_link} | "
            f"{source} | {tests} | {receipt} |"
        )
    return "\n".join(rows)


def _implementation_links(
    repository: Path,
    document: Path,
    block: PairBlock,
    profile: ChecklistProfile,
) -> str:
    """Render source and test links from one document."""

    owner = (repository / dict(profile.repository_roots)[block.repository]).resolve()
    links = [
        _link(document, owner / item, Path(item).name)
        for item in (*block.source_paths, *block.test_paths)
    ]
    return " · ".join(links)


def _link(document: Path, target: Path, label: str, fragment: str | None = None) -> str:
    """Return one escaped document-relative Markdown link."""

    relative = Path(os.path.relpath(target, document.parent)).as_posix()
    destination = quote(relative, safe="/")
    suffix = f"#{quote(fragment, safe='-._~')}" if fragment is not None else ""
    escaped_label = (
        label.replace("\\", "\\\\")
        .replace("[", "\\[")
        .replace("]", "\\]")
        .replace("|", "\\|")
    )
    return f"[{escaped_label}]({destination}{suffix})"


def _receipt_link(repository: Path, document: Path, receipt: str | None) -> str:
    """Render the current receipt or the initial-state marker."""

    if receipt is None:
        return "None"
    return _link(document, repository / receipt, "receipt")


def _shell_command(
    repository: Path,
    gate: GateCommand,
    roots: dict[str, Path],
) -> str:
    """Render one structured gate as a shell command for a human operator."""

    working_directory = (
        repository / roots[gate.repository] / gate.working_directory
    ).resolve()
    command = shlex.join(gate.argv)
    if gate.environment:
        assignments = " ".join(
            f"{key}={shlex.quote(value)}" for key, value in gate.environment
        )
        command = f"{assignments} {command}"
    return f"cd {shlex.quote(working_directory.as_posix())}\n{command}"


def _next_transition(
    repository: Path,
    pair_block_id: str,
    status: str,
    profile: ChecklistProfile,
) -> str:
    """Render a repository-rooted lifecycle operation for direct execution."""

    lifecycle = profile.lifecycle
    prefix = f"cd {shlex.quote(repository.resolve().as_posix())}\n"
    if status.startswith(lifecycle.waiting_prefix):
        return "# Waiting for a declared dependency."
    if status == lifecycle.drafting_status:
        return (
            prefix
            + "python -m tools.pairblock_status.pairblock_controller gate "
            + shlex.quote(pair_block_id)
        )
    for event, before, _ in lifecycle.transitions:
        if status == before:
            return (
                prefix
                + "python -m tools.pairblock_status.pairblock_controller advance "
                f"{pair_block_id} {event} --evidence-kind KIND "
                "--evidence-target TARGET --evidence-revision REVISION"
            )
    return "# Lifecycle complete."
